### PR TITLE
detect new configuration checkbox and reply/tag accordingly

### PR DESCRIPTION
**Pull request by stapelberg**
related to https://github.com/i3/i3/pull/4297

### CODE REVIEW

**Comment by stapelberg** [comment]
@Airblader Is this what you had in mind? Let me know if yes, and I’ll deploy and let you know when it’s ready for testing.

**Comment by orestisfl** [comment]
I was thinking about:

1. Adding the comment in all enhancement requests
2. Adding a label (e.g. `requires-configuration`) when ` [x] This feature requires new configuration and/or commands ` is checked

**Comment by Airblader** [comment]
@orestisfl Isn't that what this is?

**Review by Airblader — APPROVED** [review]

**Review by orestisfl — APPROVED** [review]
Hmm, I must have misread it before, sorry

**Comment by stapelberg** [comment]
Now deployed and tested successfully at https://github.com/i3/i3/issues/4306

**Comment by Airblader** [comment]
Thanks!

**Pull request merged**
